refactor(create-post): moved form to new page
gsolyom/meme_sanctuary pull request #12
Opened 2019-04-25 12:18 UTC by gsolyom

2019-04-25 12:28 UTC, lolismatic requested changes

2019-04-25 12:28 UTC, lolismatic commented on src/app/features/posts/components/create-post/create-post.component.ts
> +export class CreatePostComponent {
Rename to NewPostComponent to better reflect the user url

2019-04-29 13:44 UTC, gsolyom commented
Never mind the new request. Found an issue with the animation. Please postpone the review until further notice.

2019-04-30 09:55 UTC, gsolyom commented
Issue solved, PR is review-ready.

2019-04-30 12:39 UTC, lolismatic approved these changes

2019-04-30 13:07 UTC, merged